echo "This shell command has not been updated yet, disable driver, ensure GoPro WiFi, run captureImage.py"
echo "Change directory"
echo "run switcher python script - connect to wifi network for ftp"
echo "run ftp script to retrieve target"
echo "run switcher python script - switch to gopro wifi"
echo "run capture image script"
